### PR TITLE
Updated and improved the docs

### PR DESCRIPTION
**Pull request by vaishnaviverma**
Corrected a few grammatical errors in the document and updated some texts as well.

### CODE REVIEW

**Comment by Chintan2108** [comment]
Hi @vaishnaviverma 
Thank you for your PR.
The updations are good.

Before I merge the PR, I just want to confirm if this is as a part of the [DSC-SLoP](https://slop.dscdaiict.in/) program? 
Please let me know if it is, so I can give you points accordingly.

**Comment by vaishnaviverma** [comment]
Hi,

The updations are not a part of SLoP. I applied but I was not selected I
guess.

But this is indeed a part of my Hacktoberfest PRs, if that helps.

Have a great day! :)

Regards,
Vaishnavi Verma

**Comment by Chintan2108** [comment]
@vaishnaviverma That's great! I'm merging your PR. You can go ahead and delete the branch.

**Comment by vaishnaviverma** [comment]
Thank you :)
Have a great weekend

**Pull request merged**
