### PR TITLE
Emotion/Expression Detector

### LINKED ISSUE #10: Emotion Detection using Facial Expression
* Currently CHEERBOT uses only textual data and NLP based sentiment analysis to detect user's emotional state
- [ ] Train a model on facial expressions to detect the user's emotional state

### PR DESCRIPTION
**Pull request by PrathameshDeshpande**
Fixes #10 

This is the Emotion/Expression Detector For ChatBot to keep track of the emotion of the person. It has 7 classes (Angry, Disgust, Fear, Happy, Neutral, Sad, Surprise)

### CODE REVIEW

**Comment by Chintan2108** [comment]
Hi @PrathameshDeshpande, good work!
Please do the following:
* Follow the PR guidelines as posted on gitter/as can be found on the readme
* Have a comprehensive step-based write-up on how to run your model (you can also mention that you have placed your model in the archives zip)
* Provide snapshots of the model prediction for each class in your PR description
* Provide info on how you trained your model, and train dataset directory structure

**Comment by PrathameshDeshpande** [comment]
Fixes #10 
* **This PR fixes the issue of training facial expressions model to detect the user's emotional state**
* **Libraries used are -**
**1) Numpy 1.19.4**
**2) opencv-python 4.4.0.46**
**3) tensorflow 2.3.1**
**4) scikit-learn 0.23.2**
* **The logic Behind this is to use transfer learning to build a multiclass classification model to classify different emotional states for our chatbot**
* **In order to run the program please follow these steps-**
**1)Clone the Repo in your system**
**2)Unpack the archives zip to get weights of the trained model and model.json**
**3)Provide the correct path for Harcascade file, weight file, JSON file**
**4)Run the Python Program using CLI**
* **The model is fine-tuned using resnet transfer learning on Kaggle Face expression recognition dataset for over 50 epochs**
* **The Snapshots of the working model are given below**
bandicam 2020-11-06 00-00-08-295
bandicam 2020-11-05 23-58-04-406
bandicam 2020-11-05 23-58-15-883
bandicam 2020-11-06 00-06-48-901

* **The Directory structure for training, testing and validation is given below**
C:.
├───train
│       ├───angry
│       ├───disgust
│       ├───fear
│       ├───happy
│       ├───neutral
│       ├───sad
│       └───surprise
└───validation
        ├───angry
        ├───disgust
        ├───fear
        ├───happy
        ├───neutral
        ├───sad
        └───surprise

**Review by Chintan2108 — APPROVED** [review]
Great work @PrathameshDeshpande

**Comment by Chintan2108** [comment]
give @PrathameshDeshpande 150 points

**Pull request merged**
